{% set version = '7.3-14' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-class
  version: {{ version|replace("-", "_") }}

source:
  fn: class_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/class_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/class/class_{{ version }}.tar.gz
  sha256: 18b876dbc18bebe6a00890eab7d04ef72b903ba0049d5ce50731406a82426b9c

build:
  merge_build_host: True  # [win]
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-mass

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('class')"           # [not win]
    - "\"%R%\" -e \"library('class')\""  # [win]

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Various functions for classification, including k-nearest neighbour, Learning Vector
    Quantization and Self-Organizing Maps.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - dbast
