{% set version = '7.3-14' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-class
  version: {{ version|replace("-", "_") }}

source:
  fn: class_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/class_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/class/class_{{ version }}.tar.gz
  sha256: 18b876dbc18bebe6a00890eab7d04ef72b903ba0049d5ce50731406a82426b9c

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('class')"  # [not win]
    - "\"%R%\" -e \"library('class')\""  # [win]

about:
  home: http://www.stats.ox.ac.uk/pub/MASS4/
  license: GPL-2 | GPL-3
  summary: Various functions for classification, including k-nearest neighbour, Learning Vector
    Quantization and Self-Organizing Maps.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
